task:
  #task_root: "./evaluation_examples/"  # 从此目录中读取修改时间最靠后的json，作为任务列表
  task_file: "evaluation_examples/test_for_train.json" # test_for_train.json: 154个task，用于训练
  osworld_root: "./evaluation_examples/examples_processed"  # root of task detail json, organized by domain
  resume: False # 是否忽略已经跑出结果的task，测pass@1时可设为True

storage:
  root: "results/val_trainset150_rft_step20" # trainer的run_id
  
  splitter:
    output_dir: "splitted_traj"  # 基于storage.root的相对路径
    window_size: 5
    stride_size: 5
    max_images:  &max_images 5   # 最多保存的图片数量
    max_texts: &max_texts 35   # 最多保留的文本条数

model:
  ckpt_path: &default_ckpt_path '/workspace/computer-use/verl/checkpoints/verl_osworld_grpo/osworld_all_feasible_reward_script_grpo_k8s_0813_df5pnk2g/global_step_20/actor/huggingface' #'/capacity/userdata/vcfenxd75jiv/workshops/workshop-bcdfd6ea-b06a-4ea9-9c99-43477f3bf4ab/verl/checkpoints/verl_osworld_grpo/osworld_all_feasible_reward_script_grpo_k8s_20250822_nq5yekbp/global_step_20/actor/huggingface'  # "/workspace/computer-use/verl/checkpoints/verl_osworld_grpo/osworld_all_feasible_reward_script_grpo_k8s_0813_mfel74uq/global_step_64/actor/huggingface"
  replicas:   8           # 并行启动的vllm serve数量，可以写很大，实际最大不超过GPU数
  base_port:  8000

  host: &service_host "0.0.0.0"
  service_port: &service_port 15959
  service_endpoint: "http://localhost:15959"

  vllm_params:
    gpu_memory_utilization: 0.9


env:
  server_url: &server "http://112.125.88.107:4999"
  user_token: &token "user5"

coordinator:
  max_concurrent_envs: 60   # 最大并行启动的环境数量
  max_task_queue_size: 1     # 全部任务循环几次
  rollout_n: &rollout_n 1     #  


runner:
  max_steps:  100
  max_images: *max_images    #在storage.splitter的同名字段中修改
  max_texts:  *max_texts    
  write_to_mysql: True    # 数据是否保存至mysql中  
  rollout_n: *rollout_n

  env:
    server_url: *server
    user_token: *token
    max_retries: 3
    action_space: "pyautogui"
    screen_size: (1920, 1080)
    headless: True
    os_type: "Ubuntu"
    require_a11y_tree: False

  model_pool:     # vllm serve的相关参数
    timeout:  10
    retries:    5
    backoff:    2
    frequency_penalty: 1
    temperature: 0
    top_p: 1
    max_tokens: 500
    seed: 1
    ckpt_path: *default_ckpt_path

mysql:
  username: "teamx"
  password: "#C!D123^-c12"
  host: "112.125.88.107"
  port: 5906
  database: "TeamX_BIGAI"