task:
  #task_root: "./evaluation_examples/"  # 从此目录中读取修改时间最靠后的json，作为任务列表
  task_file: "evaluation_examples/test_all.json"
  osworld_root: "./evaluation_examples/examples_processed_03_plan_image"  # root of task detail json, organized by domain
  resume: False # 是否忽略已经跑出结果的task，测pass@1时可设为True

storage:
  root: "results/pass32_20250812_1010_all_pass32_gpu8_env70"
  
  splitter:
    output_dir: "splitted_traj"  # 基于storage.root的相对路径
    window_size: 5
    stride_size: 5
    max_images:  &max_images 5   # 最多保存的图片数量
    max_texts: &max_texts 30   # 最多保留的文本条数

model:
  checkpoint_dir: ""      # 模型热更新，尚未实现
  ckpt_path: "/capacity/userdata/vcfenxd75jiv/shichenrui/ui_tars/ByteDance-Seed/UI-TARS-1.5"
  replicas:   8           # 并行启动的vllm serve数量，可以写很大，实际最大不超过GPU数
  base_port:  8000

env:
  server_url: &server "http://112.125.88.107:4999"
  user_token: &token "user5"

coordinator:
  max_concurrent_envs: 70     # 最大并行启动的环境数量
  max_task_queue_size: 1     # 全部任务循环几次
  rollout_n: 32     #  


runner:
  max_steps:  100
  max_images: *max_images    #在storage.splitter的同名字段中修改
  max_texts:  *max_texts    
  write_to_mysql: False    # 数据是否保存至mysql中  

  env:
    server_url: *server
    user_token: *token
    max_retries: 3
    action_space: "pyautogui"
    screen_size: (1920, 1080)
    headless: True
    os_type: "Ubuntu"
    require_a11y_tree: False

  prelaunched_model:    # 分支方案，未成功获取vllm serve端口时，读取已启动的模型端口，用于测试
    base_url: "https://sv-98272fdc-4f22-4a25-ba0e-7d51a37448d3-8000-x-defau-51acffd7d9.sproxy.hd-01.alayanew.com:22443/v1"
    model: "ui_tars_1.5"
    frequency_penalty: 1
    max_tokens: 500
    temperature: 0.7
    top_p: 1
    seed: 1

  model_pool:     # vllm serve的相关参数
    timeout:  10
    retries:    5
    backoff:    2
    frequency_penalty: 1
    temperature: 0.7
    top_p: 1
    max_tokens: 500
    seed: 
    endpoint: "http://127.0.0.1:8000"
mysql:
  username: "teamx"
  password: "#C!D123^-c12"
  host: "112.125.88.107"
  port: 5906
  database: "TeamX_BIGAI"
  